# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('cr_time', models.CharField(max_length=100, null=True)),
                ('short_url', models.URLField(null=True)),
                ('clicks', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
