# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
