# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160704_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='cr_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
