# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160705_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='cr_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.URLField(max_length=100, null=True, unique=True),
        ),
    ]
